### ISSUE TITLE
Type scale generator doesn't match with the Design Type scale

### ISSUE THREAD

**Issue by Classy-Bear** [material-components/material-components-flutter#29]
* The dart code from the [Type scale generator](https://material.io/design/typography/#) is deprecated and shouldn't be used. It will be awesome to have this properly generated. 
![Screen Shot 2020-03-22 at 11 29 46 PM](https://user-images.githubusercontent.com/37255403/77278250-38f92380-6c95-11ea-9f62-24c40cbc8e79.png)

* I couldn't pick the same font in 'Headlines & Subtitles' and 'Body & Captions'. This only apply for a **few** fonts in my case I used Oxanium couldn't find it in 'Body & Captions' section .
![Screen Shot 2020-03-22 at 11 29 06 PM](https://user-images.githubusercontent.com/37255403/77278285-50d0a780-6c95-11ea-92f3-852837706bf3.png)

* The Example type scale photo/(sketch file) doesn't match with the scale generator.

**Comment by willlarche** [comment]
Thanks for reporting this! We'll work with the type scale generator team on updating the generated code and forward the rest of your feed back to them too.

**Comment by mikekosulin** [comment]
Flutter generator should use new names:
https://material.io/design/typography/the-type-system.html#type-scale
```
OLD NAME      NEW NAME
----------------------
display4      headline1
display3      headline2
display2      headline3
display1      headline4
headline      headline5
title         headline6
subhead       subtitle1
subtitle      subtitle2
body1         bodyText2
body2         bodyText1
button        button
caption       caption
overline      overline
```

**Comment by Classy-Bear** [comment]
Closing this issue because [type scale generator](https://material.io/design/typography/the-type-system.html) exports the [TextTheme](https://api.flutter.dev/flutter/material/TextTheme-class.html) class with the 2018 specs.
