### ISSUE TITLE
Icon Button Splash overflow

### ISSUE THREAD

**Issue by sidrao2006** [material-components/material-components-flutter#60]
According to [this flutter issue](https://github.com/flutter/issues/64702), the `IconButton`'s default `splashRadius` is too large even for material's `AppBar`. As mentioned in the issue, the splash overflows and has to be set manually.

Was this intended? As the splash doesn't even fit in the default material `AppBar`.

**Comment by willlarche** [comment]
Hey, @sidrao2006 ! I'll respond to you over in the Flutter repo. We keep all the issues over there. Stay tuned.

**Comment by sidrao2006** [comment]
Ok thanks a lot
