### ISSUE TITLE
where are sample codes ?

### ISSUE THREAD

**Issue by maxime-aubry** [material-components/material-components-flutter#65]
Hello.

I don't find sample codes for material components on your website.
Could you tell me where i could find them please ?

Thanks.

**Comment by rami-a** [comment]
Hi @maxime-aubry, we have sample code for some components here: https://material.io/develop/flutter and we are working on making sure we cover all material components there.

Additionally you can find code samples for every material component in the flutter gallery repo at https://github.com/flutter/gallery/ which is hosted at gallery.flutter.dev. Hope this helps!
